/**
 * LoL Draft Assistant - Counter & Synergy Database
 * 
 * 代表的なチャンピオン間の相性（カウンター・シナジー）を定義したメタデータです。
 * ユーザーがアプリ起動後にUIから追加・編集・削除することが可能で、
 * カスタマイズされたデータは LocalStorage に保存されます。
 */

const DEFAULT_DRAFT_DATABASE = {
  // カウンター関係 (キー: チャンピオンID, 値: そのチャンピオンに強いチャンピオンIDのリスト)
  counters: {
    "Aatrox": ["Fiora", "Jax", "Irelia", "Kled", "Singed"],
    "Ahri": ["Yasuo", "Zed", "LeBlanc", "Talon", "Vex"],
    "Akali": ["Galio", "Pantheon", "LeBlanc", "Vex"],
    "Akshan": ["Yasuo", "Irelia", "Zed", "Talon"],
    "Alistar": ["Morgana", "Janna", "Lulu", "Thresh"],
    "Amumu": ["Olaf", "Graves", "Shaco"],
    "Anivia": ["Kassadin", "Zed", "Yasuo", "Fizz"],
    "Annie": ["Brand", "Xerath", "VelKoz", "Syndra"],
    "Aphelios": ["Twitch", "KogMaw", "Jinx", "Tristana"],
    "Ashe": ["Ezreal", "Tristana", "Yasuo", "Draven"],
    "AurelionSol": ["Fizz", "Zed", "Katarina", "Yone"],
    "Azir": ["Ziggs", "Xerath", "Kassadin", "Syndra"],
    "Bard": ["Morgana", "Thresh", "Blitzcrank"],
    "BelVeth": ["Jax", "Rammus", "Fiddlesticks"],
    "Blitzcrank": ["Morgana", "Sivir", "Ezreal", "Leona", "Taric"],
    "Brand": ["Xerath", "VelKoz", "Lux"],
    "Braum": ["Morgana", "Zyra", "Lulu", "Senna"],
    "Briar": ["Jax", "Rammus", "Shen", "Lulu"],
    "Caitlyn": ["Jinx", "Tristana", "Sivir", "Varus"],
    "Camille": ["Jax", "Fiora", "Renekton", "Shen"],
    "Cassiopeia": ["Xerath", "VelKoz", "Syndra", "Anivia"],
    "ChoGath": ["Vayne", "Fiora", "Gwen", "Kled"],
    "Corki": ["Yasuo", "Zed", "Talon", "LeBlanc"],
    "Darius": ["Teemo", "Quinn", "Kayle", "Kennen", "Jayce", "Gnar"],
    "Diana": ["Mordekaiser", "Galio", "Yasuo"],
    "DrMundo": ["Vayne", "Fiora", "Gwen", "Trundle"],
    "Draven": ["Caitlyn", "Ashe", "Varus", "Senna"],
    "Ekko": ["Kassadin", "LeBlanc", "Yasuo", "Yone"],
    "Elise": ["Olaf", "Rengar", "Karthus"],
    "Evelynn": ["RekSai", "Rengar", "LeeSin", "Warwick"],
    "Ezreal": ["Draven", "Caitlyn", "Tristana", "Twitch"],
    "Fiddlesticks": ["Olaf", "XinZhao", "Udyr"],
    "Fiora": ["Jax", "Malphite", "Kayle", "Teemo"],
    "Fizz": ["Kassadin", "Lissandra", "Galio", "Ryze"],
    "Galio": ["Yasuo", "Yone", "Zed", "Talon"],
    "Gangplank": ["Kayle", "Fiora", "Riven", "Lucian"],
    "Garen": ["Teemo", "Quinn", "Kayle", "Camille", "Darius"],
    "Gnar": ["Irelia", "Yasuo", "Fiora", "Teemo"],
    "Gragas": ["Sylas", "Mordekaiser", "Gwen"],
    "Graves": ["Olaf", "Rammus", "Nidalee"],
    "Gwen": ["Fiora", "Jax", "Riven", "Tryndamere"],
    "Hecarim": ["Thresh", "Janna", "Lulu", "Jax"],
    "Heimerdinger": ["Syndra", "Xerath", "VelKoz"],
    "Illaoi": ["Kayle", "Teemo", "Quinn", "Vayne"],
    "Irelia": ["Jax", "Fiora", "Renekton", "Sett"],
    "Ivern": ["Graves", "Kindred", "Rengar"],
    "Janna": ["Blitzcrank", "Sona", "Nami", "Yuumi"],
    "JarvanIV": ["Jax", "Graves", "Poppy", "Gragas"],
    "Jax": ["Malphite", "Singed", "Garen", "Teemo", "ChoGath"],
    "Jayce": ["Irelia", "Yasuo", "Fiora", "Wukong"],
    "Jhin": ["Caitlyn", "Tristana", "Lucian", "Draven"],
    "Jinx": ["Ezreal", "Twitch", "Tristana", "Sivir"],
    "Kaisa": ["Caitlyn", "Ashe", "Draven", "Jhin"],
    "Kalista": ["Ashe", "Caitlyn", "Senna", "Nasus"],
    "Karma": ["Xerath", "Lux", "VelKoz"],
    "Karthus": ["Soraka", "Kassadin", "Fizz", "Evelynn"],
    "Kassadin": ["Pantheon", "Talon", "Zed", "Lucian", "Tristana"],
    "Katarina": ["Kassadin", "Lissandra", "Galio", "Malzahar", "Pantheon"],
    "Kayle": ["Irelia", "Jax", "Fiora", "Tryndamere", "Nasus"],
    "Kayn": ["Jax", "Graves", "Poppy", "Lulu"],
    "Kennen": ["Irelia", "Yasuo", "Fiora", "Jayce"],
    "Khazix": ["Rammus", "Elise", "Lulu", "LeeSin"],
    "Kindred": ["Jax", "Graves", "LeeSin", "MasterYi"],
    "Kled": ["Fiora", "Jax", "Shen"],
    "KogMaw": ["Blitzcrank", "Nautilus", "Pyke", "Thresh", "Draven"],
    "LeBlanc": ["Kassadin", "Lissandra", "Galio", "Yasuo", "Diana"],
    "LeeSin": ["Rammus", "Jax", "Udyr", "Poppy"],
    "Leona": ["Morgana", "Thresh", "Janna", "Lulu", "Braum"],
    "Lillia": ["Vi", "LeeSin", "Rengar", "JarvanIV"],
    "Lissandra": ["Kassadin", "Xerath", "VelKoz", "Syndra"],
    "Lucian": ["Caitlyn", "Ashe", "Senna"],
    "Lulu": ["Morgana", "Blitzcrank", "Thresh", "Nautilus"],
    "Lux": ["Yasuo", "Zed", "Fizz", "Katarina"],
    "Malphite": ["Sylas", "Mordekaiser", "Gwen", "Illaoi", "ChoGath"],
    "Malzahar": ["Syndra", "Xerath", "Lux", "Gangplank"],
    "Maokai": ["Sylas", "Mordekaiser", "Trundle"],
    "MasterYi": ["Jax", "Rammus", "Lulu", "Fiddlesticks", "Malphite"],
    "Milio": ["Blitzcrank", "Nautilus", "Pyke", "Thresh"],
    "MissFortune": ["Yasuo", "Braum", "Tristana", "Samira"],
    "Mordekaiser": ["Fiora", "Gwen", "Jax", "Vayne", "Olaf"],
    "Morgana": ["Karma", "Zyra", "Senna", "Lulu"],
    "Naafiri": ["Jax", "Shen", "Rammus"],
    "Nami": ["Blitzcrank", "Nautilus", "Thresh", "Lulu"],
    "Nasus": ["Teemo", "Gnar", "Kayle", "Vayne", "Illaoi", "Sylas"],
    "Nautilus": ["Morgana", "Braum", "Lulu", "Taric"],
    "Neeko": ["Xerath", "VelKoz", "Syndra"],
    "Nidalee": ["Olaf", "Rengar", "Karthus", "Yasuo"],
    "Nilah": ["Xayah", "Caitlyn", "Ashe", "Senna"],
    "Nocturne": ["Jax", "Graves", "Olaf", "Lulu"],
    "Nunu": ["Olaf", "Trundle", "Karthus"],
    "Olaf": ["Kayle", "Teemo", "Vayne", "Ashe"],
    "Orianna": ["Kassadin", "Zed", "Yasuo", "Yone"],
    "Ornn": ["Fiora", "Gwen", "Sylas", "Vayne", "Trundle"],
    "Pantheon": ["Malphite", "Ornn", "Shen", "Morgana"],
    "Poppy": ["Darius", "Gnar", "Kayle", "Morgana"],
    "Pyke": ["Morgana", "Lulu", "Soraka", "Janna"],
    "Qiyana": ["Galio", "Kassadin", "Lissandra", "Yasuo"],
    "Quinn": ["Irelia", "Yasuo", "Malphite"],
    "Rakan": ["Morgana", "Janna", "Thresh", "Lulu"],
    "Rammus": ["Vayne", "Gwen", "Mordekaiser", "Lulu"],
    "RekSai": ["Jax", "Graves", "Poppy"],
    "Rell": ["Morgana", "Janna", "Thresh", "Braum"],
    "Renekton": ["Gnar", "Teemo", "Kayle", "Quinn", "Illaoi", "Jax"],
    "Rengar": ["Jax", "Rammus", "Poppy", "Lulu"],
    "Riven": ["Jax", "Fiora", "Renekton", "Kennen", "Malphite"],
    "Rumble": ["Sylas", "Yone", "Yasuo", "Gwen"],
    "Ryze": ["Kassadin", "Xerath", "VelKoz", "Syndra"],
    "Samira": ["Alistar", "Nautilus", "Leona", "Braum", "Yasuo"],
    "Sejuani": ["Olaf", "Trundle", "Sylas", "Gwen"],
    "Senna": ["Blitzcrank", "Nautilus", "Pyke", "Thresh"],
    "Seraphine": ["Yasuo", "Zed", "Fizz", "Blitzcrank"],
    "Sett": ["Jax", "Fiora", "Vayne", "Gwen", "Renekton"],
    "Shaco": ["RekSai", "LeeSin", "Lulu"],
    "Shen": ["Gwen", "Vayne", "Sylas", "Fiora"],
    "Shyvana": ["Olaf", "Trundle", "Jax"],
    "Singed": ["Vayne", "Kayle", "Teemo", "Gnar"],
    "Sion": ["Vayne", "Fiora", "Gwen", "Sylas", "Trundle"],
    "Sivir": ["Draven", "Vayne", "Twitch", "Tristana"],
    "Skarner": ["Olaf", "Trundle", "Lulu"],
    "Sona": ["Blitzcrank", "Nautilus", "Pyke", "Thresh"],
    "Soraka": ["Blitzcrank", "Nautilus", "Pyke", "Thresh", "Katarina"],
    "Swain": ["Vayne", "Fiora", "Gwen", "Sylas"],
    "Sylas": ["Galio", "Kassadin", "Lissandra", "Malzahar"],
    "Syndra": ["Fizz", "Zed", "Yasuo", "Kassadin"],
    "TahmKench": ["Vayne", "Fiora", "Gwen", "Trundle"],
    "Taliyah": ["Zed", "Yasuo", "Fizz", "Kassadin"],
    "Talon": ["Galio", "Kassadin", "Lissandra", "Yasuo"],
    "Taric": ["Morgana", "Zyra", "Lux"],
    "Teemo": ["Ryze", "Cassiopeia", "Yone", "Yasuo", "Pantheon"],
    "Thresh": ["Morgana", "Braum", "Lulu", "Janna"],
    "Tristana": ["Caitlyn", "Draven", "Ashe"],
    "Trundle": ["Jax", "Fiora", "Teemo", "Kennen"],
    "Tryndamere": ["Jax", "Malphite", "Fiora", "Teemo", "Nasus"],
    "TwistedFate": ["Fizz", "Zed", "Yasuo", "Kassadin", "Nocturne"],
    "Twitch": ["Draven", "Caitlyn", "Tristana"],
    "Udyr": ["Jax", "Olaf", "Trundle"],
    "Urgot": ["Jax", "Fiora", "Vayne", "Kayle"],
    "Varus": ["Yasuo", "Braum", "Samira", "Tristana"],
    "Vayne": ["Caitlyn", "Ashe", "Draven", "Jhin", "Tristana"],
    "Veigar": ["Fizz", "Zed", "Kassadin", "Yasuo"],
    "VelKoz": ["Fizz", "Zed", "Yasuo", "Katarina"],
    "Vex": ["Zed", "Talon", "Kassadin"],
    "Vi": ["Jax", "Poppy", "Lulu", "Morgana"],
    "Viego": ["Jax", "Rammus", "Poppy", "Lulu"],
    "Viktor": ["Kassadin", "Zed", "Yasuo", "Fizz"],
    "Vladimir": ["Kassadin", "Anivia", "Malzahar", "Ryze"],
    "Volibear": ["Jax", "Fiora", "Vayne", "Kayle"],
    "Warwick": ["Jax", "Olaf", "Rammus"],
    "Wukong": ["Jax", "Fiora", "Renekton"],
    "Xayah": ["Caitlyn", "Ashe", "Draven"],
    "Xerath": ["Fizz", "Zed", "Yasuo", "Katarina"],
    "XinZhao": ["Jax", "Rammus", "Poppy"],
    "Yasuo": ["Renekton", "Pantheon", "Jax", "Fiora", "Malphite"],
    "Yone": ["Pantheon", "Renekton", "Jax", "Fiora", "Yasuo"],
    "Yorick": ["Jax", "Fiora", "Irelia", "Tryndamere"],
    "Yuumi": ["Blitzcrank", "Nautilus", "Pyke", "Thresh"],
    "Zac": ["Olaf", "Trundle", "Poppy"],
    "Zed": ["Lissandra", "Malphite", "Kayle", "Zhonyas", "Galio"],
    "Zeri": ["Lulu", "Yuumi", "Janna", "Karma"],
    "Ziggs": ["Yasuo", "Zed", "Fizz", "Kassadin"],
    "Zilean": ["Morgana", "Blitzcrank", "Thresh"],
    "Zoe": ["Fizz", "Zed", "Yasuo", "Kassadin"],
    "Zyra": ["Xerath", "Lux", "VelKoz"]
  },

  // シナジー関係 (キー: チャンピオンID, 値: 相性の良いチャンピオンIDのリスト)
  synergies: {
    // ADC & Support synergies
    "Lucian": ["Nami", "Milio", "Braum", "Lulu", "Yuumi"],
    "Nami": ["Lucian", "Jhin", "Ezreal", "KogMaw"],
    "Milio": ["KogMaw", "Jinx", "Aphelios", "Lucian"],
    "Lulu": ["KogMaw", "Jinx", "Vayne", "Twitch", "Tristana"],
    "KogMaw": ["Lulu", "Milio", "Braum", "Janna"],
    "Jinx": ["Lulu", "Milio", "Thresh", "Blitzcrank"],
    "Vayne": ["Lulu", "Janna", "Thresh", "Braum"],
    "Samira": ["Nautilus", "Alistar", "Rell", "Thresh", "Leona", "Pyke"],
    "Nautilus": ["Samira", "Kaisa", "Yasuo", "Draven", "Jinx"],
    "Alistar": ["Samira", "Yasuo", "Kalista"],
    "Rell": ["Samira", "Kaisa", "Orianna"],
    "Leona": ["Samira", "Draven", "Kaisa"],
    "Kaisa": ["Nautilus", "Rell", "Leona", "Thresh", "Blitzcrank", "Alistar"],
    "Kalista": ["Thresh", "Alistar", "Nautilus", "Taric", "Rell"],
    "Thresh": ["Kalista", "Jinx", "Aphelios", "Draven", "Vayne"],
    "Twitch": ["Lulu", "Yuumi", "Rakan", "Zilean"],
    "Yuumi": ["Twitch", "Zeri", "Hecarim", "Garen", "Ezreal", "Kayn"],
    "Zeri": ["Lulu", "Yuumi", "Janna", "Karma"],

    // Womb Combo / Hard CC Synergies (ノックアップ連携など)
    "Yasuo": ["Malphite", "Diana", "Yone", "Alistar", "Gragas", "LeeSin", "Vi", "Ornn", "Zac"],
    "Malphite": ["Yasuo", "Orianna", "MissFortune", "Samira", "Galio"],
    "Diana": ["Yasuo", "Orianna", "Yone", "Vladimir"],
    "Yone": ["Yasuo", "Diana", "Malphite", "Ornn"],
    "Orianna": ["Malphite", "JarvanIV", "Rengar", "Diana", "Wukong", "Zac", "Hecarim"],
    "JarvanIV": ["Orianna", "Galio", "MissFortune", "Rumble", "Anivia"],
    "Galio": ["JarvanIV", "Camille", "Malphite", "Nocturne", "Hecarim"],
    "Camille": ["Galio", "Sejuani", "Taliyah"],
    "Nocturne": ["Galio", "Shen", "TwistedFate"],
    "Shen": ["Nocturne", "Evelynn", "Twitch", "Rengar", "Kayn"],

    // Poke / Siege Synergies
    "Jayce": ["Nidalee", "Varus", "Xerath", "Ziggs", "Ezreal"],
    "Nidalee": ["Jayce", "Renekton", "Pantheon", "Leona"],
    "Varus": ["Jayce", "Xerath", "Ziggs", "Karma"]
  },

  // チャンピオンの個別属性メタデータ（AD/AP/TANK分類、構成特性タグ）
  champDetails: {
    "Aatrox": { damageType: "AD", tags: ["CC", "Dive"] },
    "Ahri": { damageType: "AP", tags: ["CC", "Dive"] },
    "Akali": { damageType: "AP", tags: ["Dive"] },
    "Alistar": { damageType: "AP", tags: ["CC", "WombCombo"] },
    "Aphelios": { damageType: "AD", tags: ["HyperCarry"] },
    "Ashe": { damageType: "AD", tags: ["CC", "Poke"] },
    "Azir": { damageType: "AP", tags: ["HyperCarry", "CC"] },
    "Bard": { damageType: "AP", tags: ["CC"] },
    "Blitzcrank": { damageType: "AP", tags: ["CC"] },
    "Brand": { damageType: "AP", tags: ["WombCombo"] },
    "Braum": { damageType: "TANK", tags: ["Shield", "CC"] },
    "Caitlyn": { damageType: "AD", tags: ["Poke"] },
    "Camille": { damageType: "AD", tags: ["Dive"] },
    "Cassiopeia": { damageType: "AP", tags: ["HyperCarry", "CC"] },
    "Darius": { damageType: "AD", tags: ["Fighter"] },
    "Diana": { damageType: "AP", tags: ["CC", "WombCombo", "Dive"] },
    "DrMundo": { damageType: "TANK", tags: ["Fighter"] },
    "Draven": { damageType: "AD", tags: ["HyperCarry"] },
    "Ezreal": { damageType: "AD", tags: ["Poke"] },
    "Fiddlesticks": { damageType: "AP", tags: ["CC", "WombCombo"] },
    "Fiora": { damageType: "AD", tags: ["Fighter"] },
    "Fizz": { damageType: "AP", tags: ["Dive"] },
    "Galio": { damageType: "AP", tags: ["CC", "WombCombo", "Shield"] },
    "Garen": { damageType: "AD", tags: ["Fighter"] },
    "Gnar": { damageType: "AD", tags: ["CC", "WombCombo"] },
    "Gragas": { damageType: "AP", tags: ["CC", "WombCombo"] },
    "Graves": { damageType: "AD", tags: ["Fighter"] },
    "Gwen": { damageType: "AP", tags: ["HyperCarry"] },
    "Hecarim": { damageType: "AD", tags: ["CC", "Dive"] },
    "Illaoi": { damageType: "AD", tags: ["Fighter"] },
    "Irelia": { damageType: "AD", tags: ["Fighter", "Dive"] },
    "Janna": { damageType: "AP", tags: ["Shield", "CC"] },
    "JarvanIV": { damageType: "AD", tags: ["CC", "WombCombo", "Dive"] },
    "Jax": { damageType: "AD", tags: ["Fighter", "Dive"] },
    "Jayce": { damageType: "AD", tags: ["Poke"] },
    "Jhin": { damageType: "AD", tags: ["CC", "Poke"] },
    "Jinx": { damageType: "AD", tags: ["HyperCarry"] },
    "Kaisa": { damageType: "AD", tags: ["Dive", "HyperCarry"] },
    "Kalista": { damageType: "AD", tags: ["HyperCarry"] },
    "Karma": { damageType: "AP", tags: ["Shield", "Poke"] },
    "Karthus": { damageType: "AP", tags: ["WombCombo"] },
    "Kassadin": { damageType: "AP", tags: ["HyperCarry", "Dive"] },
    "Katarina": { damageType: "AP", tags: ["WombCombo", "Dive"] },
    "Kayle": { damageType: "AP", tags: ["HyperCarry"] },
    "Kayn": { damageType: "AD", tags: ["Dive"] },
    "Kennen": { damageType: "AP", tags: ["CC", "WombCombo"] },
    "Khazix": { damageType: "AD", tags: ["Dive"] },
    "KogMaw": { damageType: "AD", tags: ["HyperCarry"] },
    "LeBlanc": { damageType: "AP", tags: ["Dive"] },
    "LeeSin": { damageType: "AD", tags: ["Dive", "CC"] },
    "Leona": { damageType: "TANK", tags: ["CC", "WombCombo"] },
    "Lillia": { damageType: "AP", tags: ["CC", "WombCombo"] },
    "Lissandra": { damageType: "AP", tags: ["CC", "WombCombo"] },
    "Lucian": { damageType: "AD", tags: ["Fighter"] },
    "Lulu": { damageType: "AP", tags: ["Shield", "CC"] },
    "Lux": { damageType: "AP", tags: ["Poke", "CC"] },
    "Malphite": { damageType: "TANK", tags: ["CC", "WombCombo"] },
    "Malzahar": { damageType: "AP", tags: ["CC"] },
    "Maokai": { damageType: "TANK", tags: ["CC", "WombCombo"] },
    "MasterYi": { damageType: "AD", tags: ["HyperCarry"] },
    "Milio": { damageType: "AP", tags: ["Shield"] },
    "MissFortune": { damageType: "AD", tags: ["WombCombo"] },
    "Mordekaiser": { damageType: "AP", tags: ["Fighter"] },
    "Morgana": { damageType: "AP", tags: ["CC", "Shield"] },
    "Nami": { damageType: "AP", tags: ["Shield", "CC"] },
    "Nasus": { damageType: "AD", tags: ["Fighter"] },
    "Nautilus": { damageType: "TANK", tags: ["CC", "WombCombo"] },
    "Nidalee": { damageType: "AP", tags: ["Poke"] },
    "Nocturne": { damageType: "AD", tags: ["Dive", "CC"] },
    "Nunu": { damageType: "TANK", tags: ["CC"] },
    "Olaf": { damageType: "AD", tags: ["Fighter"] },
    "Orianna": { damageType: "AP", tags: ["CC", "WombCombo", "Shield"] },
    "Ornn": { damageType: "TANK", tags: ["CC", "WombCombo"] },
    "Pantheon": { damageType: "AD", tags: ["CC", "Dive"] },
    "Poppy": { damageType: "TANK", tags: ["CC"] },
    "Pyke": { damageType: "AD", tags: ["CC", "Dive"] },
    "Rakan": { damageType: "AP", tags: ["CC", "WombCombo", "Shield", "Dive"] },
    "Rammus": { damageType: "TANK", tags: ["CC"] },
    "Rell": { damageType: "TANK", tags: ["CC", "WombCombo"] },
    "Renekton": { damageType: "AD", tags: ["Fighter", "Dive"] },
    "Rengar": { damageType: "AD", tags: ["Dive"] },
    "Riven": { damageType: "AD", tags: ["Fighter", "Dive"] },
    "Rumble": { damageType: "AP", tags: ["WombCombo", "Poke"] },
    "Ryze": { damageType: "AP", tags: ["HyperCarry"] },
    "Samira": { damageType: "AD", tags: ["WombCombo", "HyperCarry"] },
    "Sejuani": { damageType: "TANK", tags: ["CC", "WombCombo"] },
    "Senna": { damageType: "AD", tags: ["Shield", "HyperCarry"] },
    "Seraphine": { damageType: "AP", tags: ["CC", "WombCombo", "Shield"] },
    "Sett": { damageType: "AD", tags: ["Fighter", "CC"] },
    "Shaco": { damageType: "AD", tags: ["Dive"] },
    "Shen": { damageType: "TANK", tags: ["Shield", "CC"] },
    "Shyvana": { damageType: "AP", tags: ["Fighter"] },
    "Sion": { damageType: "TANK", tags: ["CC", "WombCombo"] },
    "Sivir": { damageType: "AD", tags: ["HyperCarry"] },
    "Sona": { damageType: "AP", tags: ["Shield", "CC", "WombCombo"] },
    "Soraka": { damageType: "AP", tags: ["Shield"] },
    "Swain": { damageType: "AP", tags: ["WombCombo"] },
    "Sylas": { damageType: "AP", tags: ["Fighter", "Dive"] },
    "Syndra": { damageType: "AP", tags: ["CC", "Poke"] },
    "TahmKench": { damageType: "TANK", tags: ["CC", "Shield"] },
    "Taliyah": { damageType: "AP", tags: ["CC", "Poke"] },
    "Talon": { damageType: "AD", tags: ["Dive"] },
    "Taric": { damageType: "TANK", tags: ["Shield", "CC"] },
    "Teemo": { damageType: "AP", tags: ["Poke"] },
    "Thresh": { damageType: "AP", tags: ["CC", "Shield"] },
    "Tristana": { damageType: "AD", tags: ["HyperCarry", "Dive"] },
    "Trundle": { damageType: "AD", tags: ["Fighter"] },
    "Tryndamere": { damageType: "AD", tags: ["Fighter"] },
    "TwistedFate": { damageType: "AP", tags: ["CC"] },
    "Twitch": { damageType: "AD", tags: ["HyperCarry"] },
    "Udyr": { damageType: "AD", tags: ["Fighter"] },
    "Urgot": { damageType: "AD", tags: ["Fighter"] },
    "Varus": { damageType: "AD", tags: ["Poke", "CC"] },
    "Vayne": { damageType: "AD", tags: ["HyperCarry"] },
    "Veigar": { damageType: "AP", tags: ["CC", "WombCombo"] },
    "VelKoz": { damageType: "AP", tags: ["Poke", "WombCombo"] },
    "Vex": { damageType: "AP", tags: ["CC", "WombCombo", "Dive"] },
    "Vi": { damageType: "AD", tags: ["CC", "Dive"] },
    "Viego": { damageType: "AD", tags: ["Fighter", "Dive"] },
    "Viktor": { damageType: "AP", tags: ["HyperCarry", "Poke"] },
    "Vladimir": { damageType: "AP", tags: ["HyperCarry", "WombCombo"] },
    "Volibear": { damageType: "AD", tags: ["Fighter"] },
    "Warwick": { damageType: "AD", tags: ["Fighter"] },
    "Wukong": { damageType: "AD", tags: ["CC", "WombCombo", "Dive"] },
    "Xayah": { damageType: "AD", tags: ["HyperCarry"] },
    "Xerath": { damageType: "AP", tags: ["Poke"] },
    "XinZhao": { damageType: "AD", tags: ["Fighter", "Dive"] },
    "Yasuo": { damageType: "AD", tags: ["CC", "WombCombo", "Dive"] },
    "Yone": { damageType: "AD", tags: ["CC", "WombCombo", "Dive"] },
    "Yorick": { damageType: "AD", tags: ["Fighter"] },
    "Yuumi": { damageType: "AP", tags: ["Shield"] },
    "Zac": { damageType: "TANK", tags: ["CC", "WombCombo", "Dive"] },
    "Zed": { damageType: "AD", tags: ["Dive"] },
    "Zeri": { damageType: "AD", tags: ["HyperCarry"] },
    "Ziggs": { damageType: "AP", tags: ["Poke", "WombCombo"] },
    "Zilean": { damageType: "AP", tags: ["Shield", "CC"] },
    "Zoe": { damageType: "AP", tags: ["Poke", "CC"] },
    "Zyra": { damageType: "AP", tags: ["CC", "WombCombo"] }
  },

  // ランクマッチで一般的に強力・高BAN率のチャンピオン（フルパランク用メタデータ）
  metaChampions: {
    "TOP": ["Aatrox", "Fiora", "Jax", "Darius", "Gwen"],
    "JUNGLE": ["LeeSin", "Viego", "Graves", "Nocturne", "JarvanIV"],
    "MIDDLE": ["Yasuo", "Yone", "Zed", "Ahri", "Sylas"],
    "BOTTOM": ["Ezreal", "Jinx", "KaiSa", "Caitlyn", "Vayne"],
    "UTILITY": ["Thresh", "Nautilus", "Lulu", "Nami", "Blitzcrank"]
  }
};
